List<String> name = [
  "Arjuna Vishada Yoga",
  "Sankhya Yoga",
  "Karma Yoga",
  "gnana-Karma-Sanyasa Yog",
  "Karma-Sanyasa Yoga",
  "Atma-Samyama Yoga",
  "gnana-Vignana Yoga",
  "Aksara-ParaBrahma Yoga",
  "Raja-Vidya-Raja-Guhya Yoga",
  "Vibhuti Yoga",
  "Vishwarupa-Darsana Yoga",
  "Bhakti Yoga",
  "Ksetra-Ksetrajna-Vibhaga Yoga",
  "Gunatraya-Vibhaga Yoga",
  "Purushottama Yoga",
  "Daivasura-Sampad-Vibhaga Yoga",
  "Shraddhatraya-Vibhaga Yoga",
  "Moksha-Sanyasa Yoga",
];
